# Generated by Django 3.1.7 on 2021-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chosen_time',
            field=models.DateTimeField(null=True),
        ),
    ]
