# Generated by Django 3.1.7 on 2021-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0001_added_invite_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='senttime',
            field=models.DateTimeField(),
        ),
    ]
