# Generated by Django 3.1.5 on 2021-02-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='enddate',
            new_name='endDate',
        ),
    ]
