# Generated by Django 3.1.5 on 2021-02-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0002_auto_20210205_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startTime',
        ),
    ]
