# Generated by Django 3.1.5 on 2021-02-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0002_auto_20210206_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
