# Generated by Django 3.1.5 on 2021-03-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedge', '0002_auto_20210304_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('event', 'time', 'date')},
        ),
    ]
