# Generated by Django 3.1.5 on 2021-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0003_auto_20210205_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
