# Generated by Django 3.1.5 on 2021-03-04 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedge', '0003_added_creator_field_to_timeslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupEvent',
            new_name='Participant',
        ),
    ]
