# Generated by Django 3.1.5 on 2021-03-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0004_auto_20210323_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chosen_timeslot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='schedge.potentialtimeslot'),
        ),
    ]
