# Generated by Django 3.1.6 on 2021-02-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0004_auto_20210205_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('C', 'Concluded'), ('U', 'Unresolved')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='hostID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedge.user'),
        ),
    ]
