# Generated by Django 3.1.5 on 2021-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0005_auto_20210208_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/media/default.jpg', upload_to=''),
        ),
    ]
