# Generated by Django 3.1.5 on 2021-03-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0005_auto_20210323_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chosen_timeslot',
        ),
        migrations.AddField(
            model_name='potentialtimeslot',
            name='chosen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potentialtimeslot',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedge.event'),
            preserve_default=False,
        ),
    ]
