# Generated by Django 3.1.6 on 2021-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0005_auto_20210211_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hostID',
            field=models.IntegerField(),
        ),
    ]
