# Generated by Django 3.1.5 on 2021-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0006_auto_20210323_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialtimeslot',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
