# Generated by Django 3.1.6 on 2021-02-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0007_groupevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupevent',
            name='groupID',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedge.event'),
        ),
    ]
