# Generated by Django 3.1.6 on 2021-02-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0008_auto_20210217_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedge.user'),
        ),
    ]
