# Generated by Django 3.1.5 on 2021-02-10 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0008_auto_20210208_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
