# Generated by Django 3.1.5 on 2021-02-10 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0009_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 10, 12, 47, 673237)),
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 10, 12, 47, 673224)),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
