# Generated by Django 3.1.5 on 2021-02-10 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0010_auto_20210210_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), max_length=datetime.timedelta(seconds=36000)),
        ),
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 13, 12, 0, 343697)),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 13, 12, 0, 343689)),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedge.event')),
            ],
        ),
    ]
