# Generated by Django 3.1.5 on 2021-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0012_use_timezone_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='eventid',
            new_name='event',
        ),
    ]
