# Generated by Django 3.1.6 on 2021-02-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0013_rename_event_id_to_event'),
        ('schedge', '0009_auto_20210217_1559'),
    ]

    operations = [
    ]
