# Generated by Django 3.1.6 on 2021-03-01 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0014_merge_20210222_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='enddate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hostID',
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedge.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), max_length=datetime.timedelta(seconds=36000)),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('C', 'Concluded'), ('U', 'Unresolved')], default='U', max_length=10),
        ),
    ]
