# Generated by Django 3.1.5 on 2021-02-22 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0014_merge_20210222_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='enddate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hostID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), max_length=datetime.timedelta(seconds=36000)),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('C', 'Concluded'), ('U', 'Unresolved')], default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
