# Generated by Django 3.1.6 on 2021-03-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0015_auto_20210301_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupevent',
            old_name='host',
            new_name='ishost',
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='schedge.user'),
        ),
    ]
