# Generated by Django 3.1.5 on 2021-02-22 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0015_merge_with_mypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupevent',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedge.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
