# Generated by Django 3.1.5 on 2021-02-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedge', '0016_auto_20210222_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedge.user'),
        ),
    ]
