image: ato058/schedge:latest
stages:
  #Jobs in the same stage run in parallel so we only need one stage but several jobs.
  - setup
  - test

setup:
  stage: setup

  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    
#Run functional tests.
functional:
  stage: test

  script:
    - python3 manage.py test schedge/tests/functional
  only:
    - merge_requests
    - master
#Run scenario tests.
scenario:
  stage: test
  script:
    - python3 -m pip install selenium
    - python3 manage.py test schedge/tests/scenario
  only:
    - merge_requests
    - master
