image: ato058/schedge:latest
stages:
  #Jobs in the same stage run in parallel so we only need one stage but several jobs.
  - test
    

#Run functional tests.
functional:
  stage: test

  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - python3 -m pip install tblib
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test schedge/tests/functional --parallel
  only:
    - merge_requests
    - master
#Run scenario tests.
scenario:
  stage: test
  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - python3 -m pip install tblib
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 -m pip install selenium
    - python3 manage.py test schedge/tests/scenario --parallel
  only:
    - merge_requests
    - master
