image: ato058/schedge:latest
stages:
  #Jobs in the same stage run in parallel so we only need one stage but several jobs.
  - test
  - statistics
    

#Run functional tests.
functional:
  stage: test

  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - python3 -m pip install tblib
    - python3 -m pip install django_extensions
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test schedge/tests/functional --parallel
  only:
    - merge_requests
#Run scenario tests.
scenario:
  stage: test
  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - python3 -m pip install django_extensions
    - python3 -m pip install tblib
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 -m pip install selenium
    - python3 manage.py test schedge/tests/scenario --parallel
  only:
    - merge_requests

#Create coverage report
coverage:
  stage: statistics
  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - python3 -m pip install tblib
    - python3 -m pip install selenium
    - python3 -m pip install coverage
    - python3 -m pip install django_extensions
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - coverage run
    - coverage xml
    - coverage report
  only:
    - master
  artifacts:
    reports:
      cobertura: /builds/zig-inc/schedge/ziginc/coverage.xml

documentation:
  stage: statistics
  allow_failure: True
  script:
    - apt-get update
    - python3 -m pip install Pillow
    - python3 -m pip install django-notifications-hq
    - python3 -m pip install tblib
    - python3 -m pip install selenium
    - python3 -m pip install django_extensions
    - python3 -m pip install docstr_coverage
    - cd ziginc
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - echo For more thourogh report check the artifacts form this pipeline
    - docstr-coverage 2>&1 | tee docu_coverage.yaml
  only:
    - master
  artifacts:
    paths:
      - /builds/zig-inc/schedge/ziginc/docu_coverage.yaml
    when: always
