stages:
  - test

test:
  stage: test
  tags:
    - django
  script:
    - python3 -m pip install Pillow
    - python3 -m pip install selenium
    - cd ziginc
    - python3 manage.py test schedge/tests
  only:
    - merge_requests
    - master
